"""dashboard "New File" picker — folder-first new file workflow.

The picker owns only explicit overlay state:

  - the current directory,
  - the shallow (one level) list of navigable entries,
  - the selection index and scroll offset,
  - the file-name being typed.

It never instantiates an editor Buffer and never scans the filesystem tree,
so the overlay stays memory-bounded and the "type your filename straight
into the editor" mistake is impossible.  Creation is delegated back to the
editor only after the user confirms a valid name.

Key handling is pure and deterministic (``handle_key`` returns an explicit
action), so the overlay state machine is unit-testable without a terminal.
The companion ``draw`` function paints the overlay in one pass so the TUI can
compose it over the dashboard with a single refresh.
"""
from __future__ import annotations

import os
from typing import List, Optional, Tuple

import curses

from .explorer import FileExplorer
from . import completion
from .render import safe_render

# Normalized key names.  ``CTRL_1`` is a sentinel the TUI produces when it
# recognizes a CSI-u Ctrl+1 sequence (ESC[49;5u / ESC[49:5u); it can never be
# generated by a plain key and therefore cannot collide with Ctrl+Q.
ENTER = "\n"
ESC = "\x1b"
CTRL_1 = "__ctrl_1__"


class NewFilePicker:
    """Deterministic state for the folder-first New File overlay."""

    def __init__(self, start_dir: str | None = None) -> None:
        self.active = False
        self.cwd = os.path.abspath(os.path.expanduser(start_dir or "~"))
        self.entries: List[Tuple[str, str, bool]] = []  # (name, path, is_dir)
        self.selected = 0
        self.scroll = 0
        self.filename = ""
        self.message = ""

    # ------------------------------------------------------------------ #
    # Lifecycle
    # ------------------------------------------------------------------ #
    def open(self, start_dir: str | None = None) -> None:
        """Show the picker, re-rooted at *start_dir* (default: home)."""
        if start_dir:
            self.cwd = os.path.abspath(os.path.expanduser(start_dir))
        self.filename = ""
        self.message = ""
        self.active = True
        self._refresh()

    def close(self) -> None:
        self.active = False

    # ------------------------------------------------------------------ #
    # Listing
    # ------------------------------------------------------------------ #
    def _shallow_list(self, directory: str) -> List[Tuple[str, str, bool]]:
        """One level of *directory*, filtered like the file tree.

        Only directories are surfaced for navigation; that keeps the list
        small and the overlay cheap (RAM spec: shallow listing only). Files
        under the selected folder are created by typing their name.
        """
        try:
            names = os.listdir(directory)
        except OSError:
            self.message = f"Cannot list {directory}"
            return []
        kept: List[Tuple[str, str, bool]] = []
        for name in sorted(names, key=str.lower):
            if name.startswith(".") and name not in {".config"}:
                continue
            if name in FileExplorer.ALWAYS_IGNORED_NAMES:
                continue
            if any(name.endswith(s) for s in FileExplorer.ALWAYS_IGNORED_SUFFIXES):
                continue
            full = os.path.join(directory, name)
            if os.path.isdir(full):
                kept.append((name, full, True))
        return kept

    def _refresh(self) -> None:
        self.entries = self._shallow_list(self.cwd)
        n = len(self.entries)
        self.selected = max(0, min(self.selected, n - 1))
        self.scroll = max(0, min(self.scroll, n - 1))

    def at_root(self) -> bool:
        """True when *cwd* cannot climb higher (filesystem root)."""
        return os.path.dirname(self.cwd) == self.cwd

    # ------------------------------------------------------------------ #
    # Navigation
    # ------------------------------------------------------------------ #
    def move(self, dy: int) -> None:
        """Move the selection by *dy*, clamped to the entries."""
        if self.entries:
            self.selected = max(0, min(self.selected + dy, len(self.entries) - 1))

    def enter_selected(self) -> None:
        """Enter the selected directory (re-list it as *cwd*)."""
        if 0 <= self.selected < len(self.entries):
            _name, path, is_dir = self.entries[self.selected]
            if is_dir:
                self.cwd = path
                self._refresh()

    def go_to_parent(self) -> None:
        """Climb one level; at the filesystem root just report and stay."""
        if self.at_root():
            self.message = "Already at filesystem root"
            return
        old = self.cwd
        self.cwd = os.path.dirname(old)
        self._refresh()
        # Select the folder we just climbed out of.
        for i, (name, path, is_dir) in enumerate(self.entries):
            if is_dir and path == old:
                self.selected = i
                self.scroll = max(0, i)
                break

    def backspace(self) -> None:
        """Delete the last filename char, or climb to the parent folder when
        the filename is already empty (spec behavior)."""
        if self.filename:
            self.filename = self.filename[:-1]
        else:
            self.go_to_parent()

    def visible_entries(self, view_h: int) -> List[int]:
        """Row indices to draw in a *view_h*-row window, selection always
        visible (the scroll offset auto-adjusts to keep it on screen)."""
        n = len(self.entries)
        if view_h <= 0:
            self.scroll = 0
            return []
        self.scroll = max(0, min(self.scroll, max(0, n - view_h)))
        if self.selected < self.scroll:
            self.scroll = self.selected
        elif self.selected >= self.scroll + view_h:
            self.scroll = self.selected - view_h + 1
        return list(range(self.scroll, min(n, self.scroll + view_h)))

    # ------------------------------------------------------------------ #
    # Completion (reuses the protected path-completion API)
    # ------------------------------------------------------------------ #
    def _complete_filename(self) -> None:
        """Tab-complete the filename inside *cwd* via the existing
        ``completion`` module (same common-prefix behavior as every other
        prompt)."""
        if not self.filename:
            return
        matches = completion.complete_path(os.path.join(self.cwd, self.filename))
        names = [os.path.basename(m) for m in matches]
        if len(names) == 1:
            self.filename = names[0]
        elif len(names) > 1:
            prefix = os.path.basename(completion.common_prefix(matches))
            if prefix:
                self.filename = prefix

    # ------------------------------------------------------------------ #
    # Creation
    # ------------------------------------------------------------------ #
    @staticmethod
    def _validate_filename(name: str) -> Optional[str]:
        if not name:
            return "Filename cannot be empty"
        if name in (".", ".."):
            return f"Invalid name: {name}"
        seps = {os.sep}
        if os.altsep:
            seps.add(os.altsep)
        if "/" in name or any(sep in name for sep in seps):
            return "Filename must not contain a path separator"
        return None

    def create(self) -> Tuple[str, Optional[str]]:
        """Create the typed filename inside *cwd*.

        Returns ``(path, error)``.  On error the overlay stays alive with a
        useful message (empty name, traversal, duplicate, permission).
        """
        name = self.filename.strip()
        error = self._validate_filename(name)
        if error:
            self.message = error
            return "", error
        path = os.path.join(self.cwd, name)
        try:
            with open(path, "x"):
                pass
        except FileExistsError:
            self.message = f"'{name}' already exists"
            return path, self.message
        except OSError as exc:
            self.message = f"Cannot create file: {exc}"
            return path, self.message
        self.message = ""
        return path, None

    # ------------------------------------------------------------------ #
    # Keys
    # ------------------------------------------------------------------ #
    def handle_key(self, key) -> Optional[str]:
        """Drive one key press through the state machine.

        Returns ``None`` to keep drawing, ``"dashboard"`` to return to the
        YUKI dashboard (Esc or Ctrl+1), or ``"created"`` when a file has
        been created and the editor should open it.
        """
        if not self.active:
            return None
        if key in (ESC, CTRL_1):
            self.close()
            return "dashboard"
        if key in ("\n", "\r"):
            if self.filename.strip():
                if self.create()[1] is None:
                    self.close()
                    return "created"
                return None  # keep UI alive with the message shown
            self.enter_selected()
            return None
        if key in ("\x7f", "\b", curses.KEY_BACKSPACE):
            self.backspace()
            return None
        if key == "\t":
            self._complete_filename()
            return None
        if key == curses.KEY_UP:
            self.move(-1)
            return None
        if key == curses.KEY_DOWN:
            self.move(1)
            return None
        if isinstance(key, str) and key.isprintable():
            self.filename += key
            return None
        return None


def draw(stdscr, picker: NewFilePicker, height: int, width: int) -> None:
    """Paint the centered bordered New File overlay in one pass.

    Draws over whatever frame is already on screen (the dashboard); the TUI
    refreshes once after this returns.
    """
    inner_w = max(46, min(78, width * 72 // 100))
    inner_w = min(inner_w, width - 2)

    view_h = max(1, min(max(4, height - 14), max(1, len(picker.entries) or 1)))

    # Title + input + hint + bottom hint rows + borders.
    box_h = view_h + 8
    top = max(0, (height - box_h) // 2)
    left = max(0, (width - inner_w) // 2)

    def put(row, col, text, attr=0):
        try:
            stdscr.addstr(row, col, safe_render(text)[: max(0, width - col)], attr)
        except (curses.error, ValueError, UnicodeEncodeError):
            pass

    def row_fill(row, text, attr=0):
        put(row, left, "\u2502" + (text + " " * inner_w)[:inner_w] + "\u2502", attr)

    path = picker.cwd
    if not path.endswith(os.sep):
        path += os.sep
    shown_path = path
    if len(shown_path) > inner_w - 6:
        shown_path = "..." + shown_path[-(inner_w - 9):]

    put(top, left, "\u250c" + " NEW FILE ".center(inner_w - 2)[:inner_w - 2] + "\u2510",
        curses.A_REVERSE)
    row_fill(top + 1, f" Directory: {shown_path}", curses.A_DIM)

    filename_show = (picker.filename + "_") if picker.filename else "_"
    put(top + 2, left, "\u2502 " + f"Name: {filename_show}"
        + " " * max(0, inner_w - 2 - len(f"Name: {filename_show}"))
        + "\u2502", curses.A_UNDERLINE)
    sep = "\u251c" + "\u2500" * max(0, inner_w - 2) + "\u2524"
    put(top + 3, left, sep, curses.A_DIM)

    if picker.message:
        row_fill(top + 4, " " + picker.message, curses.A_REVERSE | curses.A_BOLD)
        list_top = top + 5
    else:
        list_top = top + 4
    list_bottom = list_top + view_h

    indices = picker.visible_entries(view_h)
    if not indices:
        row_fill(list_top, "  No accessible directories here", curses.A_DIM)
    else:
        for slot, idx in enumerate(indices):
            name = picker.entries[idx][0]
            sel = idx == picker.selected
            attr = curses.A_REVERSE if sel else 0
            display = ("\u25b6 " if sel else "   ") + name + "/"
            row_fill(list_top + slot, display, attr)

    row_fill(list_bottom,
             " \u2191/\u2193 select  Enter enter / create  Tab complete  "
             "Bksp parent  Esc back  Ctrl+1 YUKI", curses.A_DIM)
    put(min(top + box_h - 1, height - 1), left,
        "\u2514" + "\u2500" * max(0, inner_w - 2) + "\u2518", curses.A_DIM)